### ISSUE TITLE
Ionic 2 or Angular support

### ISSUE THREAD

**Issue by mrvipinkashyap** [trueicecold/phaser-scrollable#3]
Is there any guide available to use this module in Ionic 2 or Angular project.
I am trying to use this plugin in Ionic 2 app.
Following is what I have already tried:

Installed plugin using `npm install https://github.com/trueicecold/phaser-scrollable --save`
Imported it on the page I want to use it using `import * as ScrollableArea from "phaser-scrollable";`

But I am getting following error in console: `__WEBPACK_IMPORTED_MODULE_4_phaser_scrollable__ is not a constructor`

I understand that for using this module I might have to modify custom webpack configuration for Ionic Phaser project as in this example: https://github.com/jvaranam/ionic3PhaserDemo/blob/master/webpack.config.js

I already tried changing this configuration from one in above custom webpack config to:
```
var path = require( "path" );
var webpackMerge = require( "webpack-merge" );

// root directory ( useful, when config is within a sub folder )
var rootDir = path.resolve( __dirname );

// import webpack config from ionic
var ionicWebpackConfig = require( path.resolve( rootDir, "node_modules", "@ionic", "app-scripts", "config", "webpack.config" ) );

// necessary for expose loader
var phaserModule = path.join(rootDir, "node_modules", "phaser-ce");
var phaser = path.join(phaserModule, "build", "custom", "phaser-split.js");
var pixi = path.join(phaserModule, "build", "custom", "pixi.js");
var p2 = path.join(phaserModule, "build", "custom", "p2.js");
var phaserScrollable = path.join(phaserModule, "build", "custom", "phaser-scrollable.js");

module.exports = webpackMerge.smart(
  ionicWebpackConfig, {
    resolve: {
      // alias resolve (begin)
      alias: {
        "pixi": pixi,
        "p2": p2,
        "phaser-ce": phaser,
        "phaser-scrollable": phaserScrollable
      }
      // alias resolve (end)
    },
    module: {
      loaders: [
        // exposing pixi, correct phaser and p2 into global scope (begin)
        {
          test: /pixi\.js/,
          loader: "expose-loader?PIXI"
        }, {
          test: /phaser-split\.js/,
          loader: "expose-loader?Phaser"
        }, {
          test: /p2\.js/,
          loader: "expose-loader?p2"
        }, {
          test: /phaser-scrollable\.js/,
          loader: "expose-loader?ScrollableArea"
        }
        // exposing pixi, correct phaser and p2 into global scope (end)
      ]
    }
  }
);
```
and this throws following error: `Cannot find module "phaser-scrollable"`

I am already successfully able to use original plugin from which plugin is derived from i.e. 
https://github.com/jdnichollsc/Phaser-Kinetic-Scrolling-Plugin

But I want to take advantage of additional features available in this plugin.

Please let me know if this can be resolved and if this plugin can be used in Ionic app.

**Comment by trueicecold** [comment]
No angular/ionic is planned anytime soon... I stick to es5 for now...
