### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by ButsAndCats** [trueicecold/phaser-scrollable#4]
I get this error every time is scroll even outside of the scrollable element.

**Comment by trueicecold** [comment]
@ButsAndCats, Can you share an example? I don't get this issue...

**Comment by georgebutter** [comment]
https://hex-phaser.herokuapp.com/ - It's happening here.
You can login with username **guest** and password **password**

The scrollable area is the place where the messages are displayed

**Comment by trueicecold** [comment]
At first I thought it was an issue at Phaser 2.8.3 which you're using (2.6.2 and 2.9.4 worked for me, while your phaser file didn't), but then I tried using Phaser 2.8.3 directly from github, and it still works just fine. Please try to re-download your version of Phaser, or upgrade it if you can.

**Comment by georgebutter** [comment]
@trueicecold Thanks mate, I'll give that a go. 👍

**Comment by islamrobi** [comment]
Child events are not working. Is there any way to triger child event.

**Comment by trueicecold** [comment]
Please stick to issue #8 rather than commenting on unrelated topics.
