### ISSUE TITLE
error on demo page

### ISSUE THREAD

**Issue by littlee** [trueicecold/phaser-scrollable#5]
![_20171215110732](https://user-images.githubusercontent.com/7534668/34024986-3d88d5f2-e188-11e7-8a6b-767c44ac6136.png)

**Comment by itsay** [comment]
Viewsource and download to local to see the demo :)
[Image](https://raw.githubusercontent.com/trueicecold/phaser-scrollable/e2bfe0cd/lightworld_large.gif)
[scrollable](https://cdn.rawgit.com/trueicecold/phaser-scrollable/e2bfe0cd/dist/phaser-scrollable.min.js)
