### ISSUE TITLE
method to remove / update child ?

### ISSUE THREAD

**Issue by littlee** [trueicecold/phaser-scrollable#6]
I am trying to update the content in the ScrollableArea, but it only has addChild method, how do I replace the content?

**Comment by itsay** [comment]
var scroller = self.game.add.existing(new ScrollableArea(0, 0, 360, 640));

 //remove content
scroller.removeChildren(0, scroller.children.length);

//add content again

`var textStyle = {font:"30px Arial", fill:"#ffff00"};	

for (var i=0;i<10;i++) {

		for (var j=0;j<80;j++) {

			var text = game.make.text(i*330, j*30, "Yes, everything scrolls", textStyle);

			scroller.addChild(text);

		}

	}`
